- include_tasks: packages.yaml
- include_tasks: okd_tools.yaml
- include_tasks: ignition_manifests.yaml
- include_tasks: httpd_config.yaml
- include_tasks: httpd_service.yaml
- include_tasks: firewalld.yaml
